version: '3.3'
services:

  frontend:
    image: nikitairl/foodgram-front:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  backend:
    image: nikitairl/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend/staticfiles/
      - media_value:/app/backend/media/
    env_file:
      - ../backend/.env

  db:
    env_file:
      - ../backend/.env
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - '5432'

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static
      - media_value:/var/html/media
    depends_on:
      - backend
      - frontend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
